### ISSUE TITLE
Error while run the script

### ISSUE THREAD

**Issue by wilder-misfit** [froyot/aliHongbao#2]
执行脚本之后总是显示这个信息:
E
Time Elapsed: 0:00:00.006866

错误信息如下:
ft1.1: Traceback (most recent call last):
  File "alyHongBao.py", line 33, in test_
    driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
  File "/Library/Python/2.7/site-packages/appium/webdriver/webdriver.py", line 36, in **init**
    super(WebDriver, self).**init**(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "/Library/Python/2.7/site-packages/selenium-2.51.1-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 87, in **init**
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Python/2.7/site-packages/selenium-2.51.1-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 141, in start_session
    'desiredCapabilities': desired_capabilities,
  File "/Library/Python/2.7/site-packages/selenium-2.51.1-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 199, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Python/2.7/site-packages/selenium-2.51.1-py2.7.egg/selenium/webdriver/remote/remote_connection.py", line 395, in execute
    return self._request(command_info[0], url, body=data)
  File "/Library/Python/2.7/site-packages/selenium-2.51.1-py2.7.egg/selenium/webdriver/remote/remote_connection.py", line 463, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 61] Connection refused>

**Comment by froyot** [comment]
请查看[http://stackoverflow.com/questions/32207455/using-appium-driver-with-python-test-script](http://stackoverflow.com/questions/32207455/using-appium-driver-with-python-test-script),确保Appium Server已经启动
